### ISSUE TITLE
Item 화면 API 작업

### ISSUE THREAD

**Issue by HamBeomJoon** [DEPthes/3rd-MVP-NoPlanB-Android#18]
## 💼 작업 설명
Item 화면 API 작업

<br>

## ✅ To-do
- [x] Item Inventory 작업
- [x] Item 장착 적용
- [x] Item 장착 정보 저장
- [x] Item 해금
<br>
