### ISSUE TITLE
Mypage, Home 화면 캐릭터 정보 연동

### ISSUE THREAD

**Issue by HamBeomJoon** [DEPthes/3rd-MVP-NoPlanB-Android#32]
## 💼 작업 설명
Mypage, Home 화면 캐릭터 정보 연동

<br>

## ✅ To-do

- [x] Mypage 화면 레벨, 경험치 연동
- [x] Mypage 화면 캐릭터 옷 정보 연동
- [x] Home 화면 캐릭터 옷 정보 연동
<br>

## ☁️ Reference

<br>
