### ISSUE TITLE
QA 캐릭터 수정

### ISSUE THREAD

**Issue by HamBeomJoon** [DEPthes/3rd-MVP-NoPlanB-Android#51]
## 💼 작업 설명

<br>

## ✅ To-do

- [x] 캐릭터 클릭 시 말풍선 확인 필요
- [ ] 캐릭터 효과 추가 - 레벨업, 퀘스트 완료, 오늘의 퀘스트 모두 완료
- [x] 최종 레벨 달성 다이얼로그
<br>

## ☁️ Reference

<br>
